### ISSUE TITLE
Cursor gets stuck with three monitor setup

### ISSUE THREAD

**Issue by ChRav** [mgth/LittleBigMouse#421]
<img width="1619" height="1361" alt="Image" src="https://github.com/user-attachments/assets/15e216f6-a092-406b-96ee-d3fadd828279" />
Whith tree monitor setup, (laptop screen=3, thunderbolt dell display=1, 4k television=2) cursor get stuck when trying to go directly from monitor 3 to 2, and if the cursor hits the left border of the monitor number 2.

**Comment by mgth** [comment]
👋 **[LittleBigMouse 5.3.0-beta.1](https://github.com/mgth/LittleBigMouse/releases/tag/v5.3.0-beta.1) is out and should fix this.**

The v5 engine had four bugs causing the cursor to get stuck at certain screen edges until Alt-Tab: a coordinate mix-up when clamping the cursor into a screen zone, transition rectangles built with a wrong width, a randomly-initialized border resistance, and layout options (loops, max travel distance) applied *after* the zone links were computed. All identified thanks to #460 and fixed in #466.

⚠️ The beta requires the [.NET 10 Desktop Runtime (x64)](https://dotnet.microsoft.com/en-us/download/dotnet/10.0) — install it first if the app doesn't start.

Could you give it a try and report back? If the problem is gone, this issue will be closed with the stable release.

**Comment by ChRav** [comment]
Hello, unfortunatly the new beta seems to have some issues, after updating (uninstalling the old and reinstalling the new), the app doesn't show any display, just the gray screen, in list view they all sow up, for now I can't check if the issue has been solved. any suggestions why it might be? I installed .net 10 desktop runtime

thanks for the work you've been doing!

**Comment by mgth** [comment]
Thanks for testing, and sorry about that new glitch — the list view working but the location view showing only a gray screen is not something we've reproduced yet. Could you help narrow it down?

1. How many monitors, which models, resolutions and Windows scaling factors (100 %/150 %/…)?
2. Any *virtual* display in the mix (Remote Desktop, DisplayLink, spacedesk, VR/Virtual Desktop, TV)?
3. Please attach your configuration export: in the bottom-right toolbar, click the **Export configuration** button. It copies the config as JSON to your clipboard and lets you save a `LittleBigMouse.Export.gz` file — you can attach that `.gz` directly to a comment here (GitHub accepts it), or paste the clipboard content into a `.txt` file and attach that.
4. A screenshot of the gray location view would also help.

With that we should be able to reproduce your layout and fix the view.

**Comment by ChRav** [comment]
Here are some more info, i have 3 monitors:
- laptop panel, 2880x1800 @200%
- Thunderbolt display 2560x1440 @100%
- Samsung tv connected to laptop HDMI 3840x2160 @300%
The problem persists even whith the external montors disconnected.

Ive noticed that it's only the gui that doesn't show, but if started it works, I was't able to get the cursor stuck again, so the fix seems to work! I'll try to see if i can get back the GUI and do some more testing, i'm open to suggestions.

[LittleBigMouse.Export.gz](https://github.com/user-attachments/files/29713041/LittleBigMouse.Export.gz)
<img width="1906" height="1036" alt="Image" src="https://github.com/user-attachments/assets/338d674f-8d8f-415b-a2ee-c4d26ad23fad" />
<img width="1906" height="1036" alt="Image" src="https://github.com/user-attachments/assets/95fdf969-a18b-433f-ab10-6a231640efdc" />

**Comment by ChRav** [comment]
Yep, I confirm that this bug has been fixed, but even in the new stable version i still don't have a gui, i tried going back to 5.2.3.0 and the gui is there.
